### ISSUE TITLE
download installer Standalone link broken

### ISSUE THREAD

**Issue by sfonteneau** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1027]
download installer Standalone link broken

https://qgis.org/downloads/QGIS-OSGeo4W-3.26.2-2.msi  --> 404

**Comment by katagen** [comment]
The plugin page are also down. Can't install plugin anymore.

**Comment by RazRodrigues** [comment]
Looks like the plugin server is down....

**Comment by stephduff** [comment]
Same problem to  https://ftp.osuosl.org/pub/osgeo/download/qgis/windows/QGIS-OSGeo4W-3.22.10-2.msi?US
and plugin

**Comment by agiudiceandrea** [comment]
Duplicate of https://github.com/qgis/QGIS-Website/issues/1024.

@sfonteneau @stephduff the issue is fixed now. Please reload the download page refreshing your browser cache.

Anyway, the correct links to download the OSGeo4W Standalone installers are:

3.22.10: https://qgis.org/downloads/QGIS-OSGeo4W-3.22.10-1.msi | https://qgis.org/downloads/QGIS-OSGeo4W-3.22.10-1.sha256sum

3.26.2: https://qgis.org/downloads/QGIS-OSGeo4W-3.26.2-1.msi | https://qgis.org/downloads/QGIS-OSGeo4W-3.26.2-1.sha256sum

**Comment by agiudiceandrea** [comment]
@katagen @RazRodrigues, the plugin server https://plugins.qgis.org/plugins/ is again online and working.

**Comment by vivianreno** [comment]
Still not working for me. Download installer Standalone link from the site still broken

**Comment by agiudiceandrea** [comment]
@vivianreno, have you checked again after making sure your browser cache was refreshed? What is the Website language for which you experience the issue?

**Comment by vivianreno** [comment]
@agiudiceandrea I downloaded from the link you posted. Thanks!
