### ISSUE TITLE
Missing commercial support providers

### ISSUE THREAD

**Issue by shanmugamg** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#116]
The new website has missed out number of commercial support providers.

**Comment by rduivenvoorde** [comment]
Which providers are you missing? 

It helps a lot if you either point to the old resource, or just add the text you think should be on the website here.

**Comment by shanmugamg** [comment]
thanks Richard Duivenvoorde. In particular, I refer to GeoICON from Singapore. But in a mail discussion, Tim Sutton mentioned that other vendors are also missing, while transiting.

**Comment by m-kuhn** [comment]
I don't think this issue is something we could solve with the information currently provided. IMHO If a commercial support providers would like to be included, he should open an issue providing all the required details here (see http://qgis.org/en/site/forusers/commercial_support.html for examples).

Therefore I would like to request to close this issue as it's too broad and encourage commercial support providers to take appropriate action.

**Comment by mach0** [comment]
+1 Thats a very good idea .. There is even more the chance of creating a pull request of being included ..
