### ISSUE TITLE
MacOS download button labelled 3.38 downloads 3.36 instead

### ISSUE THREAD

**Issue by hemicidaris** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#1258]
## Description

The button on the website is labelled 3.38:
![Screenshot 2024-06-28 at 12-24-34 Download QGIS](https://github.com/qgis/QGIS-Website/assets/104120857/3e666379-8197-478a-9af3-d661a0877447)
but the file it downloads is actually 3.36:
![image](https://github.com/qgis/QGIS-Website/assets/104120857/438172d4-fad5-4308-ae12-5e601f8b7ba6)

Page URL: https://qgis.org/en/site/forusers/download.html

**Comment by davidafuller01** [comment]
Neither of the new builds (LTR nor Latest) have been pushed to the Downloads directory. The May'24 builds are still there.

https://download.qgis.org/downloads/macos/

qgis-macos-ltr.dmg | 2024-05-18 01:41 | 1.6G  
qgis-macos-pr.dmg | 2024-05-17 22:24 | 1.6G

**Comment by agiudiceandrea** [comment]
@davidafuller01, on the Website it is currently specified the actual QGIS version available to download
![image](https://github.com/qgis/QGIS-Website/assets/16253859/c5b76e3b-f5fd-4a07-99c4-23dfd1444cd6)

**Comment by agiudiceandrea** [comment]
@davidafuller01, on the Website, the actual QGIS versions available to downloadit are currently specified 
![image](https://github.com/qgis/QGIS-Website/assets/16253859/c5b76e3b-f5fd-4a07-99c4-23dfd1444cd6)
You need to wait for the new versions until the certificate is renewed and then the installer builds for the new versions are prepared.
You can also install the latest versions of QGIS on macOS using MacPorts https://qgis.org/en/site/forusers/alldownloads.html#macports

**Comment by davidafuller01** [comment]
@agiudiceandrea - I agree with what you are saying. The button and LTR link reflect what is on the download server, but of course that conflicts with the text at the top of the page (that text is accurate for Windows, but not macOS). This issue was opened to indicate the button / link had the wrong info... but it's actually correct.

For my part, I am curious about the cert renewal issue as the macOS release is now about 2 weeks late.

Either way, thanks for doing what you do.
