### ISSUE TITLE
Warning on download page too prominent

### ISSUE THREAD

**Issue by m-kuhn** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#150]
If you go to the download page, there is a warning about testing versions on top.
http://qgis.org/en/site/forusers/alldownloads.html

While this is generally a good thing, I don't think it increases confidence into a software if this is the first thing a user sees on the download page for **any** version (especially including stable).

I can see two possibilities to deal with this:
- Move testing downloads to a separate page where the warning may be shown
- Include a (collapsible?) box next to every unstable download and remove the one on top.

**Comment by rduivenvoorde** [comment]
I agree with you that the message now in orange etc is a little too much

But the general 'newbie' page is:
http://qgis.org/en/site/forusers/download.html
(I know that Linux users are redirected to the alldownloads.html)

There has already been a cleanup of the alldownloads in only 'stab'e' and 'testing' blocks for every OS.
But please let them stay on one page, otherwise we have to update two pages for every download/url change...

This page is a full rst page, so making things collapsable is not so easy. What about moving this warning block to the bottom of the page, and as you propose in every 'testing' block a link to that warning (like a reference: plz read the warning)?

**Comment by m-kuhn** [comment]
You are right, it's not worth sacrificing maintainability for this.

Bottom of the page + reference should solve the issue in a non-intrusive way. Sounds good to me.

**Comment by rduivenvoorde** [comment]
ok, will do this and then close this issue

**Comment by mach0** [comment]
Looks like this is already done?
