### ISSUE TITLE
Google and languages

### ISSUE THREAD

**Issue by m-kuhn** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#211]
Google seems to find results on the homepage with a random language chosen.

E.g. https://www.google.com/search?q=qgis+code+of+conduct
For me, right now, the first link points to the Spanish version (for other queries I had other languages today).

The content of the page is not (yet) translated, so from that Google cannot really tell. But as soon as a user clicks a link the page will be in Spanish.

I can only assume that [setting the language](http://www.w3.org/TR/html5/dom.html#attr-lang) in [the html tag](http://www.w3.org/TR/html5/semantics.html#the-html-element) could help user to find the proper page.

**Comment by rduivenvoorde** [comment]
it's not clear what the problem is? This code of conduct is/should indeed be available in different languages, so if I search I find the (not translated) dutch one.
I think google has a profile of me, so gives me the dutch one?

But all urls:

http://www.qgis.org/en/site/getinvolved/governance/codeofconduct/codeofconduct.html
http://www.qgis.org/nl/site/getinvolved/governance/codeofconduct/codeofconduct.html
http://www.qgis.org/de/site/getinvolved/governance/codeofconduct/codeofconduct.html
http://www.qgis.org/es/site/getinvolved/governance/codeofconduct/codeofconduct.html
etc etc

are valid isn't it?

We CAN add it dynamically though, so every language has it's own language code there. 
Is that what you mean?

What do you think Google will then show?

**Comment by m-kuhn** [comment]
The problem is, that Google is at the moment not able to make use of the language in your profile and will point you to a random site what is most likely not the NL site. I.e. you will NOT find the (untranslated) dutch one.

If the `lang` attr is added, I _assume_ that google will find the one that matches your profile.

**Comment by rduivenvoorde** [comment]
mmm, ok. We can try.

Normally browsers do find the right version. If I'm working on a dutch Windowz machine I get the dutch version (and on my english working linux machine I get english)..

but: let me find which layout file we have to copy into our theme to add this one.
I'll assign this one to myself

**Comment by DelazJ** [comment]
Is this still valid?

**Comment by rduivenvoorde** [comment]
yep, still wanting to do this. It is just adding the current language somewhere in the metadata of the page template...

**Comment by mbernasocchi** [comment]
seems fixed to me, please reopen if I'm wrong. the html tag has a lang attribute
Cheers
