### ISSUE TITLE
String not available in Transifex

### ISSUE THREAD

**Issue by DelazJ** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#244]
hi,
here (http://www2.qgis.org/en/site/getinvolved/development/index.html), the text in note frame about Osgeo userid doesn't appear in transifex and therefore is unstranslated.
There are also other strings not available in Transifex to be translated : 
- http://www2.qgis.org/pt_BR/site/forusers/index.html : documentation part
- the new text in the footpage of every page about fixing translation or reporting bug

**Comment by rduivenvoorde** [comment]
Hi, I added it some weeks ago, and have not updated the transifex strings since.

Upon next update it will be available (Normally I do the transifex update after some bigger updates of the website, not for every sentence (it takes me some time to do it).
So probably with the 2.8 release (within a couple of days) I'll update the strings.

Closing for now. Ok?

**Comment by DelazJ** [comment]
ok. 
Thanks for replying. Don't take into account my completion...
