### ISSUE TITLE
Update TLS version

### ISSUE THREAD

**Issue by ximex** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#278]
Please update the TLS version to 1.3 and add the stronger ECDHE and a SHA-256 MAC

**Comment by rduivenvoorde** [comment]
Hi We are running and older Apache, and not sure if we CAN update the server to do this.

If you provide pointers to howto's I'm happy to check if this is possible.

What is the downside of the TLS we use know?
Or.. .what do we win if we to TLS 1.3?

**Comment by ximex** [comment]
oh sorry. little mistake from me. i mean TLS 1.2 (TLS 1.3 is in development)
maybe this helps you:
https://bettercrypto.org/static/applied-crypto-hardening.pdf
https://mozilla.github.io/server-side-tls/ssl-config-generator/

this two settings are the most important ones:
- SSLProtocol
- SSLCipherSuite

TLS 1.0 is not really secure in the NSA Century. Only use this as a fallback for old clients

**Comment by rduivenvoorde** [comment]
to which https url you are referring, because we recently updated the certificate, and I did my best to get a A or A+ grade on this ssl test site....
But that is plugins.qgis.org and hub.qgis.org etc. maybe you are referring to others?
These both already do -SSLv3 
And this ciphersuite string is just too complex to understand, google 6 sites and you have 6 different recommendataions :-(

**Comment by ximex** [comment]
plugins.qgis.org gives me TLS 1.2 :+1: 
hub.qgis.org and https://qgis.org/de/site/ gives TLS 1.0 and MAC only SHA-1 instead of SHA-256

**Comment by ximex** [comment]
Looks good now. But there should be a redirect from http to https
