### ISSUE TITLE
Suggestion: add link to Mac OS X Homebrew Cask installer

### ISSUE THREAD

**Issue by MatzFan** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#281]
I have just successfully installed QGIS 2.10 on my mac thus:

```
brew cask install qgis
```

This method installs the latest (2.10) KyngChaos Mac OS X build and dependancies; GDAL, matplotlib. Given it's simplicity, I'd suggest this option is advertised, perhaps here: http://www.qgis.org/en/site/forusers/download.html

**Comment by rduivenvoorde** [comment]
@MatzFan if I understand correctly, cask is a way to install the normal QGIS installers but then via command line. I'm adviced by the mac packagers not not include it for the normal users of QGIS. I think because it hides (and therefor does not give credit) to the people who do the packaging?
If you want to discuss this further, please use the developer mailing list (I asked about this there, and got my answer from it):

https://lists.osgeo.org/pipermail/qgis-developer/2015-October/040125.html
