### ISSUE TITLE
ensure responsive layouts in common mobile devices

### ISSUE THREAD

**Issue by jj0hns0n** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#30]
Barely usable on my iPhone, better on iPad, untested on android.

**Comment by pcav** [comment]
I think sticking to basic theme as much as possible, and migrate it to BS3, is the way to go

**Comment by rduivenvoorde** [comment]
I think we broke the responsive layout on my android too

If I look at http://docs.qgis.org (our own roll of bootstrap) things work fine.

As is http://ryan-roemer.github.io/sphinx-bootstrap-theme/examples.html on my android

**Comment by rduivenvoorde** [comment]
@pacv we do stick to the ryans bootstrap-theme as much as possible. But we need to do some adjustments to implement the things that are being asked (like the dropdowns, nicer frontpages etc et).

about BS3: as soon as ryan is over, we are over too :-)

**Comment by pcav** [comment]
I think dropdowns are a good addition upstream too

**Comment by pcav** [comment]
Migration to BS3 completed upstream: http://loose-bits.com/2013/09/08/sphinx-bootstrap-theme-bootstrap-3.html

I did not have much success with my first tests, but it should be solvable.

**Comment by rduivenvoorde** [comment]
One thing we have to solve first is how we include bootstrap and css

Yulka had troubles with overriding bootstrap css, because she was not able to include her css after the bootstrap from the bootstrap sphinx theme... see #43 
That is why she hacked our own version of bootstrap into our theme: #46 is the result of that.

So I think if we first solve the order of, and which css's are included, I think we could go with upstream

**Comment by pcav** [comment]
I had a similar issue, and I solved it by using the same dir structure as in the upstream examples (in particular _static)

**Comment by rduivenvoorde** [comment]
closing as I think it is ok now. Reopen if still not working on iphone's
