### ISSUE TITLE
Replace reference to Paypal button with actual button location

### ISSUE THREAD

**Issue by pcav** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#314]
On http://qgis.org/en/site/about/sponsorship.html?highlight=paypal#list-of-donors
there is a reference to a "Paypal button on the frontpage", but there is no such button. Please put it back somewhere and update the reference here accordingly.
Same for http://qgis.org/en/site/getinvolved/governance/sponsorship/sponsorship.html?highlight=paypal#donation
where there is a "Make A Donation PayPal link provided in the left-hand menu of this website", which I also do not find.

**Comment by DelazJ** [comment]
I work on a fix (https://github.com/qgis/QGIS-Website/compare/master...DelazJ-sponsor?expand=1) of this issue and the #315 but Travis fails due to a missing reference (:ref:`QGIS-donations`).
The culprit reference does exist in the https://github.com/qgis/QGIS-Website/blob/master/source/site/getinvolved/donations.rst source file but there is also a script that overrides the content of this file. So my question(s) is(are): 
- is there no way to add link to this page using internal reference? 
- Must this page addressed only using static hyperlink (such as http://qgis.org/en/site/getinvolved/donations.html)?
