### ISSUE TITLE
Changing language is not applied if ca or fi is already selected

### ISSUE THREAD

**Issue by DelazJ** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#330]
In http://qgis.org/en/site/, changes of the language in the drop-down list are not applied if the current language is Catalan or Suomalainen. You need to manually type the language code in the url to move on.
While the url shows the right language code, the drop-down list shows English. Also (may be related?), the roadmap is not displayed for those languages.

**Comment by rduivenvoorde** [comment]
Ok, fixed for 'ca' crux is that some strings from javascript contained single quotes... Escaped them by changing these to &#39;

And fixed for 'fi' too. This was due to the addition of a newline in javascript string, thereby breaking the script...

Small fixes, had seen them before, but just did not take time to fix them.

Thanks for making it an issue!
