### ISSUE TITLE
Join Attributes by Location scrambles column contents 

### ISSUE THREAD

**Issue by MincingWords** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#380]
Download these two shapefile sets:

comm_buildings: https://drive.google.com/file/d/0ByTOrcWD6U5cYXVoQW1kS0FxNU0/view?usp=sharing
costar_abridged: https://drive.google.com/file/d/0ByTOrcWD6U5cRTREbTh0aHo3bnc/view?usp=sharing

Use Join Attributes by Location with comm_buildings as the target layer and costar_abridged as the join layer; select Take Summary / Mean and select Only keep matching records. In the resulting layer, the new attributes in the table (the ones starting with "MEAN..." have gotten scrambled by order relative to the column names. It looks as though the join layer's MEANcdd49 values have been moved up to the column named MEANZip and all of the column values to the right of that have been shoved rightward by one column.

This occurred under QGIS 2.14.5 Essen.

**Comment by DelazJ** [comment]
@MincingWords Thank you for this descriptive report but according to http://qgis.org/en/site/getinvolved/development/bugreporting.html the place to report such issue is the [issue tracker](http://hub.qgis.org). Could you please make the report there?
This repository is actually dedicated to our website issues.
Thanks.

**Comment by MincingWords** [comment]
You link to the issue tracker 404s. If you follow the link provided for "Redmine trac" on  [ http://qgis.org/en/site/getinvolved/development/bugreporting.html](http://qgis.org/en/site/getinvolved/development/bugreporting.html) there's a place to sign in, but not to register. 

If you look at the bottom of [http://www.redmine.org/projects/redmine/wiki/RedmineAccounts#My-account](http://www.redmine.org/projects/redmine/wiki/RedmineAccounts#My-account) there's a mention of a way to register. It says "On the [login screen](http://www.redmine.org/projects/redmine/wiki/RedmineLogin), click on Register. ") but if you follow that link, you see an _image_ of a login screen with "Register" up at the top but that's not clickable; it's only an image. So in that sense, perhaps there _is_ a website issue to report.

**Comment by DelazJ** [comment]
Sorry. For some reasons, github prepended my link with the current repo. As you noticed, the link is hub.qgis.org (will fix above)
I didn't know about the links you provide. Maybe are they outdated. And for sure, there are things to fix for a really straightforward reporting.

The bug and features page states that you should create an osgeo account (http://qgis.org/en/site/getinvolved/development/bugreporting.html#reports-on-applications). And then use this account to sign in on hub.qgis.org.
Note that creating account may take time for validation due to a mantra request system.
