### ISSUE TITLE
Unable to reactivate tools in Digitizing Toolbar and the Select Features tool

### ISSUE THREAD

**Issue by biisager** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#412]
Working with Mac OS X El Capitan (v 10.11.6) and QGIS 2.14.7-Essen.  I was following along in the training manual by attempting to digitize the provided raster (tiff format) file.  I had created the digitized features, saved them and attempted to reselect features in order to edit them.  My raster file is selected in the Layer, but the Select Features tool is greyed out (deactivated) and so are the tools in the Digitizing Toolbar.  I have removed the raster layer and added it again to retry.  No success.  I removed the raster layer, quit and restarted QGIS.  Again, no change.  This situation seems to only occur for the raster layer.

**Comment by andreasneumann** [comment]
Hi @biisager 

Note that this is not a support forum. See http://www.qgis.org/en/site/forusers/support.html for the existing support channels.

Note that in QGIS you can't edit raster layers. If you want to digitize, you need to have the concerned vector layer active - otherwise, as you noticed, the tools are greyed out.

For any other questions, please use the support channels, and not the github reop of the QGIS-Website.

Andreas

**Comment by biisager** [comment]
I apologize.  Thank you.  My mistake.
