### ISSUE TITLE
Not able to override existing images or add new ones

### ISSUE THREAD

**Issue by yulka** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#42]
The directory I am using is: source/website/static/website/images.

**Comment by jj0hns0n** [comment]
@yulka this can also be closed?

**Comment by yulka** [comment]
I did not find a way to override images, so it still needs to be addressed. I wanted to make the logo a bit smaller (50x50).

**Comment by rduivenvoorde** [comment]
hi @yulka 

there should be no  source/website/static in github

For rst based pages:
because we want (mainly in the documentation) be able to localize/i18n images (screendumps/dialogs) also we copy (current) language resources to source/website/static at Sphinx compile time:
https://github.com/qgis/QGIS-Website/blob/master/Makefile#L69
the resources/en dir is the base dir

For html based pages:
I think we use the theme/qgis-theme/static/images there. So it iis easier to point to if in css. So I think the logo you want to override is here: 
https://raw.github.com/qgis/QGIS-Website/master/resources/en/site/about/images/logo.png

Which other images exactly do you want to override? Let me know and I will point you to the places.

**Comment by yulka** [comment]
Ok, just the logo. Do you want me to resize it?

**Comment by rduivenvoorde** [comment]
yes please, and maybe call it logo70.png or so?
