### ISSUE TITLE
GPG error in Ubuntu install - public key is not available?

### ISSUE THREAD

**Issue by joemcl** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#462]
I'm attempting to sudo apt-get update in Ubuntu 17.04 after adding http://qgis.org/debian/ to my /etc/apt/sources.list,  and getting the following error message:  

"W: GPG error: http://qgis.org/debian zesty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY CAEB3DC3BDF7FB45
E: The repository 'http://qgis.org/debian zesty InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details."

I'm checking out the manpage entry, but obviously I'd prefer to do a secure update ;) . 
So can 'http://qgis.org/debian zesty InRelease' be signed/updated?
Thanks!

**Comment by dennilopez6** [comment]
Add the following lines in terminal:
wget -O - http://qgis.org/downloads/qgis-2017.gpg.key | gpg --import
gpg --fingerprint CAEB3DC3BDF7FB45

Should output:
pub   2048R/BDF7FB45 2017-08-16 [expires: 2019-08-16]
      Key fingerprint = 61E0 A086 749E 463E DE50  2255 CAEB 3DC3 BDF7 FB45
uid                  QGIS Archive Automatic Signing Key (2017) <qgis-developer@lists.osgeo.org>
sub   2048R/E959BBCF 2017-08-16 [expires: 2019-08-16]

then add: 
sudo apt-get update
gpg --export --armor CAEB3DC3BDF7FB45 | sudo apt-key add -
sudo apt-get update                  (again to see if there are still any errors)

That should resolve it.

User justinmnoor posted this on 31 March for the NO_PUBKEY 089EBE08314DF160 error:

Hi. If you have time, please review the QGIS Installers Documentation for Ubuntu Xenial 16.04.

I installed Las Palmas 2.18.5 on Ubuntu Xenial 16.04 LTS, following the instructions at:http://www.qgis.org/en/site/forusers/alldownloads.html#debian-ubuntu

The following error was generated:
W: GPG error: http://ppa.launchpad.net/ubuntugis/ubuntugis-unstable/ubuntu xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 089EBE08314DF160

I resolved it with: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key 089EBE08314DF160

This key is not referred to in the documentation. Sorry in advance if I've missed anything.

These fixed it for me.

**Comment by joemcl** [comment]
@dennilopez6 thanks so much! The steps above fixed the issue. I noticed that the steps above are now at http://www.qgis.org/en/site/forusers/alldownloads.html#debian-ubuntu .

**Comment by Semo** [comment]
Still an acceptable workaround, though it's a mess that it's not fixed in late 2018!!!

**Comment by brotherdust** [comment]
The key mentioned in this issue is now expired as of 8/16/2019. Workaround no longer works.

**Comment by hmallen** [comment]
I'm having the same issue with Debian stable. Attempts to retrieve a new key only result in retrieval of the old key and gpg reports that the key is unchanged as a result. I noticed this around the same time as user from the previous comment. It had been working fine for the last couple months.

Edit: I realized that I was actually running Debian stretch on that machine, and a switch from the 3.8 back to the 3.4 LTR repository as instructed in installer footnotes solved my problem.

**Comment by mbernasocchi** [comment]
@jef-n I just had somebody in xenial trying to install QGIS with `deb http://qgis.org/ubuntu-ltr  xenial main ubuntu-ltr` but `apt update` complains that the key on the server is outdated. do you have any hints?

**Comment by jef-n** [comment]
plain xenial has also long been dropped - 3.4 requires GDAL2 at least.  You can go for ubuntugis-ltr + ubuntugis (see also the footnotes).

**Comment by mbernasocchi** [comment]
ah, I missed the foot notes thanks

**Comment by GregorioF2** [comment]
Today on 2019  i had to addapt this solution to:

- wget -O - http://qgis.org/downloads/qgis-2019.gpg.key | gpg --import
- gpg --fingerprint 51F523511C7028C3

- sudo apt-get update
- gpg --export --armor 51F523511C7028C3 | sudo apt-key add -
- sudo apt-get update

**Comment by jef-n** [comment]
> Today on 2019 i had to addapt this solution to:

See also https://qgis.org/en/site/forusers/alldownloads.html#debian-ubuntu
