### ISSUE TITLE
Composers  Delay Project Opening

### ISSUE THREAD

**Issue by rbperezu1980** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#496]
## Sometihng that I think need be better
-When I select a qgs project with many composers included, the project delay with every composer opening. I save many composer in one qgs project, because I need these.

## -Possible Solution that I suggest:
   -Every time that we create a composer, only it should be saved with the elements and config in the qgs file, and it should not be activated and not loaded to memory until the composer is slected for use.

## Checklist
This is the issue/bug trackers for [QGIS Website](https://qgis.org).
Cleaning the queue is a process done by project maintainers, mostly on a volunteer basis.
We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items.

- [ ] I'm aware this repository is about QGIS Website and the issue I'm reporting is related to its usage. If your issue is related to QGIS Desktop, QGIS Server or documentation, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html for the right issue tracker. If you are looking for help, better use the QGIS [support channels](http://qgis.org/en/site/forusers/support.html).
- [ ] I have added a link to the page concerned by the issue

**Comment by yjacolin** [comment]
Please could you read the checklist carefully and act recording to it. Thanks. :)

**Comment by DelazJ** [comment]
Dear @rbperezu1980 ,

what @yjacolin tries to say is that this repo is about the QGIS website (hence issue you may find when browsing https://qgis.org), not about QGIS software. For issues around QGIS, please use the issue tracker https://issues.qgis.org/ or any of the support channels available from https://www.qgis.org/en/site/forusers/support.html

I am closing this issue, because it is at the wrong repo. Please re-submit at issues.qgis.org (please check whether this hasn't been already reported  - and I wonder if this behavior is not already changed in QGIS 3.0 that I invite you to try)

**Comment by andreasneumann** [comment]
For the record. The composer loading behavior is a known issues and is solved in QGIS 3.0 - it won't be solved in 2.18, however. So the way forward would be to migrate to QGIS 3 once it is considered stable enough for your purpose.

**Comment by DelazJ** [comment]
Thanks @andreasneumann for the confirmation
