### ISSUE TITLE
qgis doesn't save features added to a layer when source fields are deleted for a second time

### ISSUE THREAD

**Issue by andrejbadin** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#511]
see the video - after creation of layer, I've added features and successfully saved them, yet when repeating the workflow, features are not saved (lost forever - no change in filesize)
why do I do it this way? I want to draw the points quickly - without being forced to enter attributes for every single feature
![bug_qgis_nosave](https://user-images.githubusercontent.com/11007417/38079863-3b109922-3340-11e8-9b5a-d88c981c317e.gif)

**Comment by yjacolin** [comment]
This repository is about QGIS Website and the issue you are reporting is not related to WebSite. If your issue is related to QGIS Desktop, QGIS Server or documentation, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html for the right issue tracker. If you are looking for help, better use the QGIS [support channels](http://qgis.org/en/site/forusers/support.html).
