### ISSUE TITLE
Issue with Denmark QGIS User Group in sponsorship list

### ISSUE THREAD

**Issue by DelazJ** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#550]
Browsing https://qgis.org/fr/site/about/sponsorship.html#list-of-donors, the QGIS User Group Denmark whose sponsoring period has not yet begun has an icon bigger than the two other Gold Sponsors.

**Comment by andreasneumann** [comment]
Yes - I know about it. It is a confirmed sponsorship that I already registered for the future.

@rduivenvoorde - could you perhaps add a filter here, to filter away sponsorships of the future?

There are more such cases. Some sponsors already pay up-front before the last period ends. Or they pay already until 20xx for x years into the future.

Thank you for having a look at it.

**Comment by rduivenvoorde** [comment]
I created an issue for it, it seems a trivial change in a query: 
https://github.com/kartoza/prj.app/issues/972

Clientside I do NOT have the ability to filter because I do not have attributes but only a full description/time string. I would have to parse that with all problems that can occur with that.

About the size of the images: Because of CSS limits (or at least my css limits), I only size on either height or width. If a logo like Denmarks 'looks' too big, we have to add some whitespace around one side to make it fit better.

**Comment by rduivenvoorde** [comment]
@andreasneumann see https://github.com/kartoza/prj.app/issues/972#issuecomment-406955004 

It is ok to see them all in a list like: 
http://changelog.qgis.org/en/qgis/sponsors/list/
yes?

**Comment by DelazJ** [comment]
closing! The DEN user-group sponsoring is now in its active period (initial report fixed!) and I guess if something remains to do, there are reports at the most appropriate place to handle it.
