### ISSUE TITLE
Previous project problems on startup

### ISSUE THREAD

**Issue by jerubio** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#633]
## Description

The previous project lists looks empty on startup

## Checklist
This is the issue/bug trackers for [QGIS Website](https://qgis.org).
Cleaning the queue is a process done by project maintainers, mostly on a volunteer basis.
We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items.

- [ ] I'm aware this repository is about QGIS Website and the issue I'm reporting is related to its usage. If your issue is related to QGIS Desktop, QGIS Server or documentation, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html for the right issue tracker. If you are looking for help, better use the QGIS [support channels](http://qgis.org/en/site/forusers/support.html).
- [ ] I have added a link to the page concerned by the issue

**Comment by DelazJ** [comment]
Hi @jerubio
You don't give enough information to help us understand where the issue resides. Eg, this is the expected behavior if you're running a new user profile.
But anyway, this is not the place to report QGIS application issues. Only issues with browsing https://qgis.org are to be reported here, as mentioned in the checklist at the bottom of your message.
Look at the link in the checklist to find out where to report and remember to give them more details...
Closing.
Thanks.
