### ISSUE TITLE
Language switch seems broken if french is selected (reset to English)

### ISSUE THREAD

**Issue by DelazJ** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#680]
(_I don't know if this issue is related to french locale or the locale of my system, so if you can not replicate, may be worth you check in your locale_)
In https://qgis.org:
1. select "Français" in the language drop-down menu. The first time the actual value is set to "English" but the website URL turns to https://qgis.org/fr/site/ and is really in French.
1. If you select again "Français", it's kept in the drop-down menu until you begin browsing: it resets to English
1. Select another language, that language is shown in the menu (until you change page), but the website URL and language is still in French. 
![image](https://user-images.githubusercontent.com/7983394/65247793-4d474280-daf1-11e9-9194-fed2789726fc.png)
The only way to switch language is to manually enter the language iso in the URL
1. If in the url, you replace "fr" by anything else supported, afaics, you can select other languages, it behaves correctly: language switch and website url + language are synced. Until you select "Français".

PS: Btw (I don't know if it's related), the count down below the language switch is not displayed when the page is in French

**Comment by agiudiceandrea** [comment]
@DelazJ, it seems to me that the problem is in the french translation of the text at https://github.com/qgis/QGIS-Website/blob/master/themes/qgis-theme/languageswitch.html#L101
In Transifex is in sphinx at https://www.transifex.com/qgis/qgis-website/viewstrings/#fr/sphinx/181745287

In the translation, towards the end of the penultimate sentence, there are two "'" [apostrophe (U+0027)]:
...Que vous choisissiez de contribuer ou non, nous espérons que vous apprécierez notre travail de passionnés et vous encourageons à partager et diffuser votre copie téléchargée à tous vents, pour que **d'autres** puissent également **l'apprécier**. Avec nos cordiales salutations!

This causes an error and so the language switch doesn't work anymore.

The same problem happened with the italian translation.

To fix it, you could rewrite the sentence removing the apostrophes or substitute them e.g. with a "’" [right single quotation mark (U+2019)] like for the french translation of the text at https://github.com/qgis/QGIS-Website/blob/master/themes/qgis-theme/languageswitch.html#L102

**Comment by agiudiceandrea** [comment]
Now it works https://lists.osgeo.org/pipermail/qgis-fr-user/2019-October/000249.html
Thanks @DelazJ for fixing it.

**Comment by DelazJ** [comment]
Thanks for having shared the solution, @agiudiceandrea
