### ISSUE TITLE
Failed to Build Using Docker

### ISSUE THREAD

**Issue by ismailsunni** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#693]
## Description
I am trying to follow the README to build the website using Docker. I run the command, e.g.
```
docker run -t -i -v /home/ismailsunni/dev/python/QGIS-Website:/QGIS-Website -w=/QGIS-Website --rm=true qgis/sphinx_html make html
```
Unfortunately, I got this error:
```
Status: Downloaded newer image for qgis/sphinx_html:latest
rm -rf source/static

Removing all static content from source/static.
rm -rf source/static
Copy 'en' (base) static content to source/static.
mkdir source/static
# historically the images for the docs sub project are not in a separate docs folder
# that is why we copy site (to site) and docs/* into root in separate steps
cp -r resources/en/site source/static
Copy localized 'en' static content to source/static.
mkdir -p output/html/en
python3 scripts/mkversion.py
make: python3: Command not found
Makefile:131: recipe for target 'output/html/version.txt' failed
make: *** [output/html/version.txt] Error 127

```
I believe this is because there is no python3 inside the image. I checked by bash inside it, install python3 manually, and run the `make html` command. It works.

So, I think the fix should be easy (adding python3 to the docker image). But I am not sure where is the Dockerfile, and I don't have access to update the Docker image in docker hub also (https://hub.docker.com/r/qgis/sphinx_html)

**Comment by rduivenvoorde** [comment]
Hi @ismailsunni sorry the README is not uptodate apparently. We already moved to a newer version of the docker: qgis/sphinx_html_3 (which is all machinery based on Python3)... 

see https://github.com/qgis/QGIS-Website/blob/master/docker-run.sh#L9

Plz try again to pull that one from hub.docker.com though I'm not 100% sure I pushed it to there...

FYI: the docker file is on github too:

https://github.com/qgis/QGIS-Sysadmin/blob/master/docker/sphinx/Dockerfile-html

But to be honest, if you only want to build english docs: just create a virtual env based on REQUIREMENTS.txt, activate it and run 'make html' :-)
The docker machinery is helpfull if you want to create pdf's or builds in non western languages (because for that you need al kind of TeX and LaTex and character encodings and fonts...

**Comment by rduivenvoorde** [comment]
@ismailsunni and THANKS for trying!!! My feeling was I'm the only one on the world :-)

**Comment by ismailsunni** [comment]
Hi, @rduivenvoorde Thanks, it works now :)
I found something wrong with the website, and I want to fix it, so I try to build it here. I am more into a Docker, so I try the Docker one. Unfortunately, now I forget what is the thing that I want to fix from the website :) Hehe
