### ISSUE TITLE
Trend Micro OfficeScan reports several QGIS files as spyware

### ISSUE THREAD

**Issue by roykaho** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#758]
Hello, we have installed version 3.6.0 a long time ago.  However, we have recently received an alert from Trend Micro Office Scan that the following files are scanned as a spyware.  

C:\program files\QGIS 3.6\bin\nircmdc.exe
C:\Users\Public\Desktop\QGIS 3.6\SAGA GIS (2.3.2).lnk
C:\Users\Public\Desktop\QGIS 3.6\Qt Designer with QGIS 3.6.0 custom widgets.lnk
C:\ProgramData\Microsoft\Windows\Start Menu\Programs\QGIS 3.6\Setup.lnk
C:\ProgramData\Microsoft\Windows\Start Menu\Programs\QGIS 3.6\SAGA GIS (2.3.2).lnk
C:\ProgramData\Microsoft\Windows\Start Menu\Programs\QGIS 3.6\Qt Designer with QGIS 3.6.0 custom widgets.lnk

Does any other QGIS user encounter same or similar problem as mine?  

Is it safe to ignore the alert?  

Hope that someone can give us suggestions and comments.  Many thanks in advance.

**Comment by agiudiceandrea** [comment]
Hi roykaho, probably this is not the right repository to file this bug report. Better, https://github.com/qgis/qgis/issues.
Anyway this issue was already recently reported: see https://github.com/qgis/qgis/issues/32247 and http://osgeo-org.1560.x6.nabble.com/QGIS-has-the-virus-Hacktool-Win64-NirCMD-SM-td5437748.html

**Comment by roykaho** [comment]
Hi @agiudiceandrea , sorry that I intended to post my message to issue repo, but to QGIS-website repo accidentally.  But anyway, thanks so much for your prompt message.  

Your link is useful.
