### ISSUE TITLE
The Chinese Simplified and Chinese Traditional does not work.

### ISSUE THREAD

**Issue by sshuair** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#770]
## Description

- Chinese Simplified Page URL: https://qgis.org/zh_CN/site/
- Chinese Traditional Page URL: https://qgis.org/zh_TW/site/

Change the language to Chinese Simplified or Chinese Traditional, it does not successful change to the language, it still English.

**Comment by rduivenvoorde** [comment]
@sshuair Mmm, you are right. Thanks for letting us know.
It is probably mixing up the _CN and _TW vs the -Hans/_Hans and -Hans/_Hant mixup
Years ago we had discussions about this because certain tools could not handle one of the options...

There was another problem with the QGIS 3.10 documentation: we build/link to zh-Hans while the language tools only accept an underscore, but apparently in transifex it is zh-Hans... 

I temporarly fixed it: https://docs.qgis.org/3.10/zh_Hant/docs/index.html
But I have to figure this out again, to make this all work again...

**Comment by sshuair** [comment]
Thanks for your effort, hope this could be fixed in the future. 

BTW, there seems no zh_Hans in the documentation.

![image](https://user-images.githubusercontent.com/5787131/82847658-f4eaff00-9f21-11ea-9a2f-a63598ade9df.png)

**Comment by rduivenvoorde** [comment]
Ok, pff, I think I fixed all building quircks now at least in the qgis website (not yet in the docs):

https://qgis.org/zh-Hans/site/
https://qgis.org/zh-Hant/site/

both zh_CN and zh_TW should be redirecting to the above ones...

The fact that zh_Hans is not there is because it had such a low percentage of translation.. But I am happy to add it, if you promise to make some noise about chinese translation :-)

For Documentation I have a strange build issue, that the gettext tools do not accept zh-Hans/zh-Hant, but only want an underscore in between: zh_Hans/zh_Hant (but Transifex defines them with a '-' )

Will look into that later.

**Comment by sshuair** [comment]
Nice work, I am now focusing on QGIS Desktop translation. When desktop translation reaches about 90%, I'll translate the Website and Documentation.

**Comment by rduivenvoorde** [comment]
@sshuair Both https://qgis.org and https://docs.qgis.org/3.10/en/docs/ should now be available in zh_Hans and zh_Hant. Thanks for translating! Closing this one now.
