### ISSUE TITLE
German "Umlaute" are not supported? 

### ISSUE THREAD

**Issue by dassau** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#80]
Hi,

on the website german Umlaute are not supported, maybe there is just a language package missing?

Regards
Otto

**Comment by dassau** [comment]
Hi,

I saw it is not a transifex problem but just not properly translated text. I go through the file and try to fix it.

**Comment by rduivenvoorde** [comment]
hi Otto, please use transifex for it. OR download the file via transifex and upload it again then.

I actually thought it was already fixed by Juergen. 

After this weekend I will also create new sources. (have to find out how to do this without interfering with people who are translating at that moment)

**Comment by jef-n** [comment]
should be fixed now.
