### ISSUE TITLE
Conflicting suggestions how to cite QGIS

### ISSUE THREAD

**Issue by marisn** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#863]
How to cite QGIS is present in two places and they differ. One of them has to change.
In FAQ: https://qgis.org/en/site/getinvolved/faq/index.html#how-to-cite-qgis
In Wiki: https://issues.qgis.org/projects/qgis/wiki/QGIS_Citation_Repository

**Comment by rduivenvoorde** [comment]
@marisn I'm happy to remove the old wiki page (if I'm still able), but can you point to the error? Because recently @jonnyforestGIS did spend a lot of time to 'port' it to docs to make it translatable. But it should not have been changed I think?

See: https://github.com/qgis/QGIS-Website/pull/810

**Comment by marisn** [comment]
Citation according to FAQ: QGIS.org, 2021.
Citation according to WIKI: QGIS Development Team, 2021.

I simply just got a remark by one of my co-authors that I'm citing QGIS in a wrong way as each of us was reading different guidelines.

**Comment by jonnyforestGIS** [comment]
Hi @marisn, I think we need to use QGIS.org because QGIS.org integrate more areas such as developers, documenters, translators and so on. Using QGIS.org is more inclusive. What do you think @rduivenvoorde ? About redmine if is possible (I don't have permission rights) change de text and put a link to redirect to QGIS FAQ website.

cheers

**Comment by DelazJ** [comment]
Can we close this report? We should consider that information on the active website prevails over the information in the readonly/abandoned issues.qgis.org wiki. No?

**Comment by jonnyforestGIS** [comment]
For me yes @DelazJ.
Cheers
