### ISSUE TITLE
MAYBE THERE'S A MALWARE ON THE WEBSITE

### ISSUE THREAD

**Issue by TheLastEnvoy** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#880]
## Maybe there's a malware on QGIS site's server
Apparently, anytime I click on some link on the <https://qgis.org/pt_BR/site/> (QGIS site) an another webpage it's being open, it's called: "StripeM-inner".

Page URL: https://qgis.org/pt_BR/site/

(AVOID TO OPEN IT IF YOU ARE NOT USING A GOOD ANTIVIRUS)

**Supposed virus link:** https://m.stripe.network/inner.html#url=https%3A%2F%2Fqgis.org%2Fpt_BR%2Fsite%2F&title=Bem-vindo%20ao%20projeto%20QGIS&referrer=https%3A%2F%2Fwww.bing.com%2F&muid=NA&sid=NA&version=6&preview=false

(AVOID TO OPEN IT IF YOU ARE NOT USING A GOOD ANTIVIRUS)

(But it's happening on "subpages" too.

**Comment by jgrocha** [comment]
Oi @TheLastEnvoy 
I've opened the website and there is nothing strange on it. Seems like a local issue. Try to open the same URl on another computer (virus free!) to confirm. Or try with your mobile phone.
![Captura de ecrã de 2021-03-28 17-18-39](https://user-images.githubusercontent.com/163681/112759160-ae56ad00-8fe9-11eb-9727-fcbc82600d3b.png)

**Comment by TheLastEnvoy** [comment]
I asked a friend of mine and she got the same problem.
Try to open some things on the website, sections, etc.

I attached a print of that supposed malware page, just below:

![errorqgis](https://user-images.githubusercontent.com/81522064/112759398-311b4000-8fc9-11eb-8572-f549017d7850.png)

**Comment by jgrocha** [comment]
> I asked a friend of mine and she got the same problem.
> Try to open some things on the website, sections, etc.
> 
> I attached a print of that supposed malware page, just below:
> 
> ![errorqgis](https://user-images.githubusercontent.com/81522064/112759398-311b4000-8fc9-11eb-8572-f549017d7850.png)

Sorry, I can not replicate. I'm connected to the _real_ qgis.org website and I can navigate and follow links without issues.

![qgis website br](https://user-images.githubusercontent.com/163681/112759753-5cfbed00-8fec-11eb-9707-acad9ef155b6.png)

**Comment by rduivenvoorde** [comment]
We/QGIS uses Stripe (https://stripe.com) as payment method, so it is possible that we load the stripe javascript in too many pages (because I thought(!) it should only be loaded in the payment page), and I remember Stripe is checking some things (like if the domain is valid etc)

![Screenshot-20210329033228-1235x551](https://user-images.githubusercontent.com/731673/112776237-6bbfbf80-903f-11eb-8b59-cc8d57a7eb55.png)

stripe.network is a domain of stripe, it is mentioned for example here:
https://github.com/stripe/react-stripe-elements/issues/229

I find it mentioned here:
https://mtlynch.io/stripe-recording-its-customers/
where there is discussion if this 'domain checking' is appropriate or not... I remember first adding Stripe to the site, it was pretty difficult to debug BECAUSE of this cross domain checking

Reading the link above it could be seen as 'invasive tracking', maybe...

This is some rather tricky (and some closed payment javascript involved) though...

**Comment by TheLastEnvoy** [comment]
Hummm i think i kinda understand (I'm layman with coding, etc)
