### ISSUE TITLE
Confusion about the LTR release

### ISSUE THREAD

**Issue by wonder-sk** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#952]
The situation about the current status of LTR is confusing for users:

The qgis.org website header suggests that 3.16.13 is the latest LTR:

![image](https://user-images.githubusercontent.com/193367/142873296-866aedd5-36ae-4511-a69f-86155e86e3b8.png)

Yet the blog on the front page says 3.16.13 was reverted to 3.16.11:

![image](https://user-images.githubusercontent.com/193367/142873157-4fc413f7-168b-4202-aea7-1e6aa7580d67.png)

But downloads offer 3.16.13.

In addition to that, the "LR" and "LTR" columns on the roadmap page seem to be the other way around:

![image](https://user-images.githubusercontent.com/193367/142873695-bd7e8135-9a85-40bf-8a1a-25e34f9938eb.png)

**Comment by jef-n** [comment]
The (windows standalone) packages for 3.16.13 were updated and the packages for 3.16.14 are being build.

**Comment by hannesaddec** [comment]
Hi, 
1) I'm still confused about LTR and RECENT version in the top links at qgis.org website. Should it not be 3.22 **LTR** and 3.16.13 for recent (so no extra characters)
2) which LTR is valid at the moment ?

**Comment by jef-n** [comment]
3.22 is the current release and also a LTR release (ie. gets continued long term maintanance).  3.16 is also LTR and is currently in the LTR package repositories and gets further support until 3.22 is replaced by a newer release.   Then 3.22 will also replace 3.16 in the LTR package repositories.

**Comment by johnwbryant** [comment]
I'm also confused by the headings on the [road map page](https://www.qgis.org/en/site/getinvolved/development/roadmap.html) as @wonder-sk mentioned. It feels like these might be reversed?
![image](https://user-images.githubusercontent.com/1100600/145336155-88fb2db0-d4b2-4a38-a137-7eb8f0cc227a.png)

**Comment by johnwbryant** [comment]
Apologies for bringing it up one more time, I'm just trying to understand because I use the road map to explain it to QGIS learners in training sessions. 

The website indicates that in Feb 2022 the Latest will be 3.22.4 and the Long-Term Repo will be 3.24.0, which is the opposite of what I've been teaching.

![image](https://user-images.githubusercontent.com/1100600/145495309-6fff7ca5-aca8-492f-aa47-d6a28096089d.png)
![image](https://user-images.githubusercontent.com/1100600/145495350-11c647d7-da0a-4751-b574-79d1999812b7.png)

If you're sure it's correct I'll take your word for it.
