### ISSUE TITLE
File missing on QGIS download page

### ISSUE THREAD

**Issue by andrejbadin** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#972]
## QGIS 2.14.6 64bit files miss from download page

Please, where could I download this version of QGIS? I'm used to run it as my stable version parallel to the latest one, but the download links are dead

https://qgis.org/downloads/ >
https://qgis.org/downloads/QGIS-OSGeo4W-2.14.6-2-Setup-x86_64.exe
https://qgis.org/downloads/QGIS-OSGeo4W-2.14.6-3-Setup-x86_64.exe

**Comment by rduivenvoorde** [comment]
2.14.6? That is ancient... 

Not sure why they are not in the list, but is one of the other 2.14.x versions not close enough?

And what about moving to a more recent (LTR) version as your 'stable parallel version'? 
I'd say: 3.16 or so? (Or even better, the next LTR: 3.22)?

**Comment by rduivenvoorde** [comment]
Ah, ok, /downloads/ is spreading the load between some download places... the main one is the osgeo one, but there is also:
https://www.norbit.de/~jef/
THAT one has your version....:
https://www.norbit.de/~jef/QGIS-OSGeo4W-2.14.6-2-Setup-x86_64.exe

@jef-n any idea why osgeo is not in sync with the norbit one?

**Comment by jef-n** [comment]
On Thu, 03. Feb 2022 at 23:31:10 -0800, Richard Duivenvoorde wrote:
> Ah, ok, /downloads/ is spreading the load between some download places... the main one is the osgeo one, but there is also:
> https://www.norbit.de/~jef/
> THAT one has your version....:
> https://www.norbit.de/~jef/QGIS-OSGeo4W-2.14.6-2-Setup-x86_64.exe
> 
> @jef-n any idea why osgeo is not in sync with the norbit one?

The files are uploaded to download.osgeo.org, norbit.de and qgis.org on
release.  Only ftp.osuosl.org mirrors download.osgeo.org.  qgis.org
redirects the regular downloads to ftp.osuosl.org, download.osgeo.org and
norbit.de.

They appear on the list, because they files are also on qgis2 (earlier the file
used to not even exist on qgis2 at all - still the links would work and be
redirected).

The old files were probably cleaned out to solve some space issues on
download.osgeo.org at some point back.

Unfortunately the rrewrite.cgi was still enabled for the 2.x builds (I thought
I had disabled that), so it was still pointing downloaders elsewhere.  Now it's
disabled and the qgis.org links work (and deliver the files on qgis2).


Jürgen

-- 
Jürgen E. Fischer           norBIT GmbH             Tel. +49-4931-918175-31
Dipl.-Inf. (FH)             Rheinstraße 13          Fax. +49-4931-918175-50
Software Engineer           D-26506 Norden            https://www.norbit.de
QGIS release manager (PSC)  Germany                 IRC: jef on Libera|OFTC

norBIT Gesellschaft fuer Unternehmensberatung und Informationssysteme mbH
Rheinstrasse 13, 26506 Norden
GF: Juergen Fischer, Nils Kutscher HR: Amtsgericht Aurich HRB 100827
Datenschutzerklaerung: https://www.norbit.de/83/

**Comment by andrejbadin** [comment]
Thank you Jurgen for the quick fix and Richard for the suggestions. 

I take the ancient comment as a compliment (to QGIS).
