### ISSUE TITLE
Update website to latest versions

### ISSUE THREAD

**Issue by DelazJ** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#974]
Hi,
Is there any reason the website still mentions 3.16 as downloadable LTR and that 3.24 is still compiling[0].
I may be wrong but from [1] aren't the major OS already provided with 3.22.4 and 3.24.0?

[0] https://qgis.org/en/site/index.html, https://qgis.org/en/site/forusers/download.html#, https://qgis.org/en/site/forusers/alldownloads.html#repositories
[1] https://qgis.org/downloads/, https://qgis.org/downloads/macos, https://qgis.org/debian-ltr/dists/focal/

**Comment by DelazJ** [comment]
@jef-n ?

**Comment by agiudiceandrea** [comment]
Updated https://github.com/qgis/QGIS-Website/commit/e9baf3a2368c83c824ec9d8046e87fbfc8df51a1

**Comment by DelazJ** [comment]
Thanks for notifying @agiudiceandrea and thanks @jef-n for the fix

**Comment by jef-n** [comment]
Hi Harrissou,

On Thu, 24. Feb 2022 at 16:21:17 -0800, Harrissou Sant-anna wrote:
> Thanks for notifying @agiudiceandrea and thanks @jef-n for the fix

There was nothing to fix.  The website was just updated as usual after the
package builds were finished.

A "little bit" more delayed this time, because the ltr-3_22 tag was missing
and so the previous "nightly" run[0] still considered release-3_16 the current
LTR branch and did another nightly of that after doing the release builds of
release-3_24.

The ltr build of release-3_22 happened in the ongoing "nightly" run[1] after
the first nightly of release-3_24 and is still building master.
release-3_24 finished Thu Feb 24 17:28:03 UTC 2022, but there's no extra
notification about that and so it took some more time for me to notice.


Jürgen

[0] qgis2.qgis.org:1080/cgi-bin/build.sh?2022-02-19-0003
[1] qgis2.qgis.org:1080/cgi-bin/build.sh

-- 
Jürgen E. Fischer           norBIT GmbH             Tel. +49-4931-918175-31
Dipl.-Inf. (FH)             Rheinstraße 13          Fax. +49-4931-918175-50
Software Engineer           D-26506 Norden            https://www.norbit.de
QGIS release manager (PSC)  Germany                 IRC: jef on Libera|OFTC

norBIT Gesellschaft fuer Unternehmensberatung und Informationssysteme mbH
Rheinstrasse 13, 26506 Norden
GF: Juergen Fischer, Nils Kutscher HR: Amtsgericht Aurich HRB 100827
Datenschutzerklaerung: https://www.norbit.de/83/
