### ISSUE TITLE
64bit windows link not working

### ISSUE THREAD

**Issue by jonathan-wcc** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#98]
http://qgis.org/en/site/forusers/download.html links to:

http://qgis.org/downloads/QGIS-OSGeo4W-2.0.1-2-Setup-x86_64.exe - which gives a 404

**Comment by mach0** [comment]
In fact the link it links to is http://download2.osgeo.org/qgis/win32/QGIS-OSGeo4W-2.0.1-2-Setup-x86_64.exe

seems that the download2 is causing the issue - link works perfect without the "2" after download ..
Is this caused by any load balancer?
furthermore it seems to be only termoprary .. now everything works again .. I bet on a balancer pointing to a wrong URL

**Comment by jonathan-wcc** [comment]
Looking in - http://download2.osgeo.org/qgis/win32/ - the file simply isn't there.

Also - why is a 64bit file in a /win32/ directory?

**Comment by jef-n** [comment]
download2 now carries the installer.
