### ISSUE TITLE
Website donation link appears to be broken (similar to issue #988)

### ISSUE THREAD

**Issue by Neoprene8** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#992]
Website donation link appears to be broken (similar to issue #988 22 days ago).

I tried to make a donation. I tried Scribe in Vivaldi browser.  "Checkout" was greyed out, I couldn't proceed. Moved over to Chrome browser. Everything seemed to work until the last click, when I got the attached 404 error (similar to issue 988).  

![Screen Shot 2022-04-21 at 2 20 13 PM](https://user-images.githubusercontent.com/104171621/164556644-e05692fe-a255-4543-833b-234ef4e23368.png)

It appeared not to have worked. However, some moments later, I received an email receipt from QGIS confirming my donation. i see now there is an email address I can direct this issue to the email receipt. So I will do that too.

**Comment by wsonnekus** [comment]
note sure if related, but at the bottom of the getinvolved page(https://www.qgis.org/en/site/getinvolved/index.html), 
the link at:

`Donations: one-time financial contributions to the project - we accept [donations via a variety of channels](https://www.qgis.org/en/site/getinvolved/donations.html)`

also does not work.

**Comment by andreasneumann** [comment]
@wsonnekus  - thanks for letting us know.

It is fixed in https://github.com/qgis/QGIS-Website/commit/aa505ec1b66e40883dd89365b5c734f93ca2059e and will appear fine tomorrow after the nightly website update.

As to the main issue of @Neoprene8  - I cannot reproduce the issue. I tested with Firefox, Chrome and Edge and they all work fine. The Captcha thing is a bit annoying, but stripe.com needs this.

**Comment by andreasneumann** [comment]
@Neoprene8 - do you have javascript disabled? If yes, that might explain the issue.

**Comment by jef-n** [comment]
Alias to point qgis.org/en/site/getinvolved/donations.html added https://donate.qgis.org/ (a while ago)
